package com.daimeng.live.other;

import com.daimeng.live.R;

/**
 * Created by Administrator on 2016/3/17.
 */
public class DrawableRes {
    public static int LevelImg[] = new int[]{
            R.drawable.level_1,
            R.drawable.level_2,
            R.drawable.level_3,
            R.drawable.level_4,
            R.drawable.level_5,
            R.drawable.level_6,
            R.drawable.level_7,
            R.drawable.level_8,
            R.drawable.level_9,
            R.drawable.level_10,
            R.drawable.level_11,
            R.drawable.level_12,
            R.drawable.level_13,
            R.drawable.level_14,
            R.drawable.level_15,
            R.drawable.level_16,
            R.drawable.level_17,
            R.drawable.level_18,
            R.drawable.level_19,
            R.drawable.level_20,
            R.drawable.level_21,
            R.drawable.level_22,
            R.drawable.level_23,
            R.drawable.level_24,
            R.drawable.level_25,
            R.drawable.level_26,
            R.drawable.level_27,
            R.drawable.level_28,
            R.drawable.level_29,
            R.drawable.level_30,
            R.drawable.level_31,
            R.drawable.level_32,
            R.drawable.level_33,
            R.drawable.level_34,
            R.drawable.level_35,
            R.drawable.level_36,
            R.drawable.level_37,
            R.drawable.level_38,
            R.drawable.level_39,
            R.drawable.level_40,
            R.drawable.level_41,
            R.drawable.level_42,
            R.drawable.level_43,
            R.drawable.level_44,
            R.drawable.level_45,
            R.drawable.level_46,
            R.drawable.level_47,
            R.drawable.level_48,
            R.drawable.level_49,
            R.drawable.level_50,
            R.drawable.level_51,
            R.drawable.level_52,
            R.drawable.level_53,
            R.drawable.level_54,
            R.drawable.level_55,
            R.drawable.level_56,
            R.drawable.level_57,
            R.drawable.level_58,
            R.drawable.level_59,
            R.drawable.level_60,
          

    };

    public static int PokersImg[] = new int[]{

            R.drawable.p1_1,
            R.drawable.p1_2,
            R.drawable.p1_3,
            R.drawable.p1_4,
            R.drawable.p1_5,
            R.drawable.p1_6,
            R.drawable.p1_7,
            R.drawable.p1_8,
            R.drawable.p1_9,
            R.drawable.p1_10,
            R.drawable.p1_11,
            R.drawable.p1_12,
            R.drawable.p1_13,
            R.drawable.p1_14,

            R.drawable.p2_1,
            R.drawable.p2_2,
            R.drawable.p2_3,
            R.drawable.p2_4,
            R.drawable.p2_5,
            R.drawable.p2_6,
            R.drawable.p2_7,
            R.drawable.p2_8,
            R.drawable.p2_9,
            R.drawable.p2_10,
            R.drawable.p2_11,
            R.drawable.p2_12,
            R.drawable.p2_13,
            R.drawable.p2_14,

            R.drawable.p3_1,
            R.drawable.p3_2,
            R.drawable.p3_3,
            R.drawable.p3_4,
            R.drawable.p3_5,
            R.drawable.p3_6,
            R.drawable.p3_7,
            R.drawable.p3_8,
            R.drawable.p3_9,
            R.drawable.p3_10,
            R.drawable.p3_11,
            R.drawable.p3_12,
            R.drawable.p3_13,
            R.drawable.p3_14,

            R.drawable.p4_1,
            R.drawable.p4_2,
            R.drawable.p4_3,
            R.drawable.p4_4,
            R.drawable.p4_5,
            R.drawable.p4_6,
            R.drawable.p4_7,
            R.drawable.p4_8,
            R.drawable.p4_9,
            R.drawable.p4_10,
            R.drawable.p4_11,
            R.drawable.p4_12,
            R.drawable.p4_13,
            R.drawable.p4_14,

    };
}
